{"uuid": "0c5cfc72-a087-4757-974a-9c03d58c10a5", "children": ["08668721-3bc4-4dba-ba73-c3b11fec8ed2"], "befores": [{"name": "setup", "status": "passed", "start": 1761148092509, "stop": 1761148107541}], "afters": [{"name": "setup::0", "status": "broken", "statusDetails": {"message": "KeyboardInterrupt\n", "trace": "  File \"C:\\Users\\Ascendion\\Desktop\\Selenium\\virtual\\Lib\\site-packages\\allure_commons\\_allure.py\", line 231, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Ascendion\\Desktop\\Selenium\\virtual\\Lib\\site-packages\\_pytest\\fixtures.py\", line 939, in _teardown_yield_fixture\n    next(it)\n    ~~~~^^^^\n  File \"C:\\Users\\Ascendion\\Desktop\\Selenium\\automation_project\\conftest.py\", line 118, in setup\n    driver.quit()\n    ~~~~~~~~~~~^^\n  File \"C:\\Users\\Ascendion\\Desktop\\Selenium\\virtual\\Lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 227, in quit\n    self.service.stop()\n    ~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\Ascendion\\Desktop\\Selenium\\virtual\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 153, in stop\n    self.send_remote_shutdown_command()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\Ascendion\\Desktop\\Selenium\\virtual\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 138, in send_remote_shutdown_command\n    if not self.is_connectable():\n           ~~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\Ascendion\\Desktop\\Selenium\\virtual\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 127, in is_connectable\n    return utils.is_connectable(self.port)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"C:\\Users\\Ascendion\\Desktop\\Selenium\\virtual\\Lib\\site-packages\\selenium\\webdriver\\common\\utils.py\", line 122, in is_connectable\n    socket_ = socket.create_connection((host, port), 1)\n  File \"C:\\Users\\Ascendion\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\socket.py\", line 856, in create_connection\n    exceptions.clear()  # raise only the last error\n    ~~~~~~~~~~~~~~~~^^\n"}, "start": 1761148123407, "stop": 1761148126460}], "start": 1761148092509, "stop": 1761148126460}